<script lang="ts">
  let { label }: { label: string } = $props();

  // Svelte 5 built-in rune for generating a stable, unique ID
  const uid = $props.id();
</script>

<div class="form-group">
  <label for="{uid}-input">{label}</label>
  <div class="input-row">
    <span class="uid-badge" title="Unique ID generated by $props.id()">{uid}</span>
  </div>
</div>

<style>
  .form-group {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
    padding: 1rem;
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: var(--radius-sm);
  }

  label {
    font-weight: 500;
    color: var(--text);
  }

  .input-row {
    display: flex;
    align-items: center;
    gap: 1rem;
  }

  .uid-badge {
    font-family: var(--font-mono);
    font-size: 0.85rem;
    padding: 0.2rem 0.5rem;
    background: var(--surface-hover);
    border: 1px dashed var(--border-strong);
    border-radius: 4px;
    color: var(--text-muted);
  }
</style>
