import path from 'node:path';
import type { PreprocessorGroup } from 'svelte/compiler';
import type { MochiI18nOptions } from '../types';
import type { Handle } from '../hooks';
import { getFilter, setFilter } from '../extensions';
import { logger } from '../log';

/**
 * The client loader: registers a reactive ($state) runtime collection and
 * loads the active locale synchronously at import time, so hydrated islands
 * render the correct strings with no async flash. `setLocale()` switches the
 * locale in place (all locales are bundled via the sync proxy).
 */
function clientLoaderSource(key: string, sourceLocale: string): string {
  return `// Generated by mochi-framework i18n (Wuchale). Edit your components / wuchale.config.js instead.
import { registerLoaders, loadLocaleSync, defaultCollection } from 'wuchale/load-utils';
import { loadCatalog, loadCount } from './.wuchale/${key}.proxy.sync.js';

const runtimes = $state([]);

export const getRuntime = registerLoaders('${key}', loadCatalog, loadCount, defaultCollection(runtimes));
export const getRuntimeRx = getRuntime;

/** Switch locale in place — instant, no reload. */
export function setLocale(locale) {
  loadLocaleSync(locale);
}

loadLocaleSync(globalThis.__mochi_locale__ ?? '${sourceLocale}');
`;
}

/**
 * The server loader: reads the active locale from Mochi's globally-pinned
 * request context (set by the i18n middleware). This deliberately avoids
 * Wuchale's own AsyncLocalStorage, which would not survive Mochi's
 * per-component SSR bundling.
 */
function serverLoaderSource(key: string, sourceLocale: string): string {
  return `// Generated by mochi-framework i18n (Wuchale). Reads the active locale from the Mochi request context.
import { getRequestContext } from 'mochi-framework';
import toRuntime from 'wuchale/runtime';
import { loadCatalog } from './.wuchale/${key}.proxy.sync.js';

const cache = {};

function get(loadID = 0) {
  const locale = getRequestContext().locals.locale ?? '${sourceLocale}';
  const byLocale = (cache[locale] ??= {});
  return (byLocale[loadID] ??= toRuntime(loadCatalog(loadID, locale), locale));
}

export const getRuntime = get;
export const getRuntimeRx = get;
`;
}

async function writeIfChanged(filePath: string, contents: string): Promise<void> {
  const file = Bun.file(filePath);
  if ((await file.exists()) && (await file.text()) === contents) {
    return;
  }
  await Bun.write(filePath, contents);
}

/**
 * Seed the active locale into the page `<head>` as `window.__mochi_locale__`
 * so the client loader can load the matching catalog before islands hydrate.
 */
function seedLocale(html: string, locale: string): string {
  const value = JSON.stringify(locale).replace(/</g, '\\u003C');
  const tag = `<script>window.__mochi_locale__=${value}</script>`;
  return html.includes('<head>') ? html.replace('<head>', `<head>${tag}`) : tag + html;
}

/**
 * The dev-mode hook the file watcher uses to keep catalogs hot. `kind()` tells
 * the watcher which paths to route here — `'catalog'` for files under
 * `localesDir` (the `.po` sources and generated artifacts) and `'source'` for
 * the adapters' watched components, or `null` for everything else.
 * `handleChange()` recompiles/extracts the affected catalogs to disk and
 * reports whether the SSR/client bundles need rebuilding.
 */
export type MochiI18nChangeKind = 'catalog' | 'source';

export interface MochiI18nWatchHook {
  kind(absPath: string): MochiI18nChangeKind | null;
  handleChange(absPath: string): Promise<boolean>;
}

export interface SetupWuchaleI18nResult {
  handle: Handle;
  i18n: MochiI18nWatchHook;
}

/**
 * Wire Wuchale into Mochi. Loads the Wuchale config, generates the Mochi-aware
 * loaders, creates a Wuchale `Hub` (one adapter handler per adapter, shared
 * message index), composes the compile-time transform into the
 * `compile:preprocessors` filter, and returns the per-request locale
 * middleware plus a dev-mode catalog-watch hook.
 */
export async function setupWuchaleI18n(options: MochiI18nOptions, ctx: { development: boolean; projectRoot: string }): Promise<SetupWuchaleI18nResult> {
  const sourceLocale = options.sourceLocale ?? options.locales[0] ?? 'en';
  const configPath = path.resolve(ctx.projectRoot, options.config ?? './wuchale.config.js');

  let wuchale: typeof import('wuchale');
  try {
    wuchale = await import('wuchale');
  } catch {
    throw new Error("Mochi i18n requires the 'wuchale' package. Install it with `bun add wuchale @wuchale/svelte`.");
  }
  const { getConfig, Hub } = wuchale;

  const config = await getConfig(configPath);

  // Write the Mochi-aware loaders before creating the Hub so Wuchale's
  // getLoaderPath() detects the separate server/client `.svelte.js` pair.
  // Wuchale never overwrites them because the adapters use `loader: 'custom'`.
  const localesDir = path.resolve(ctx.projectRoot, config.localesDir);
  for (const key of Object.keys(config.adapters)) {
    await writeIfChanged(path.join(localesDir, `${key}.loader.svelte.js`), clientLoaderSource(key, sourceLocale));
    await writeIfChanged(path.join(localesDir, `${key}.loader.server.svelte.js`), serverLoaderSource(key, sourceLocale));
  }

  // 'build' mode: the per-file transform is always active and transform-only,
  // using the message index seeded from the committed catalogs. (Wuchale's
  // 'dev' mode versions its compiled artifacts for Vite HMR, which desyncs
  // Mochi's own SSR module cache — so we stay on 'build' and drive extraction
  // ourselves through `extractHub` below.)
  const hub = await Hub.create('build', () => config, ctx.projectRoot);

  // A second handler used only to (re)extract strings from changed components
  // in dev. 'cli' mode runs the extracting transform and `directVisit` persists
  // the updated `.po` catalogs; `hub` (build mode) then re-reads them so its
  // message index — and the compiled catalogs it writes — stay consistent with
  // what the SSR/client bundles reference.
  const extractHub = ctx.development ? await Hub.create('cli', () => config, ctx.projectRoot) : null;

  // Compose the Wuchale transform into the compile:preprocessors filter,
  // preserving any user-provided filter. The Hub routes each file to the
  // matching adapter (or returns no output for non-i18n files).
  const prev = getFilter('compile:preprocessors');
  setFilter('compile:preprocessors', (value, fctx) => {
    const base = prev ? prev(value, fctx) : value;
    const forServer = fctx.target === 'server';
    const wuchalePreprocessor: PreprocessorGroup = {
      name: 'wuchale',
      async markup({ content, filename }) {
        const [out] = await hub.transform(content, filename ?? fctx.filename, forServer);
        return out.code != null ? { code: out.code } : undefined;
      },
    };
    return [wuchalePreprocessor, ...base];
  });

  logger.info(`i18n: wuchale ready — locales [${options.locales.join(', ')}], source '${sourceLocale}'`);

  const handle: Handle = async ({ event, resolve }) => {
    // Locale resolution is only meaningful for page/api requests, which run
    // inside the request context. Assets, fallback and error responses run
    // outside it (so `getRequestContext()` would throw) and never need a locale.
    if (event.kind !== 'page' && event.kind !== 'api') {
      return resolve(event);
    }
    const locale = options.resolveLocale(event) ?? sourceLocale;
    event.locals.locale = locale;
    return resolve(event, { transformPage: ({ html }) => seedLocale(html, locale) });
  };

  // Watched source globs (the adapters' `files`), normalized the same way
  // Wuchale's own `globConfToArgs` does, so `owns()` matches the exact set of
  // components Wuchale extracts from. Matched relative to the project root.
  const sourcePatterns: string[] = [];
  for (const adapter of Object.values(config.adapters) as { files?: unknown }[]) {
    const files = adapter.files;
    if (typeof files === 'string') {
      sourcePatterns.push(files);
    } else if (Array.isArray(files)) {
      sourcePatterns.push(...files.filter((f): f is string => typeof f === 'string'));
    } else if (files && typeof files === 'object') {
      const include = (files as { include?: unknown }).include;
      if (typeof include === 'string') {
        sourcePatterns.push(include);
      } else if (Array.isArray(include)) {
        sourcePatterns.push(...include.filter((f): f is string => typeof f === 'string'));
      }
    }
  }
  const sourceGlobs = sourcePatterns.map((p) => new Bun.Glob(p));

  // The source-locale catalog; re-reading it pulls every locale back into `hub`
  // (the owner's `loadStorage` loads all locales) after an extraction.
  const sourcePoPath = path.join(localesDir, `${sourceLocale}.po`);

  const isCatalogPath = (absPath: string): boolean => {
    const abs = path.resolve(absPath);
    return abs === localesDir || abs.startsWith(localesDir + path.sep);
  };
  const isSourcePath = (absPath: string): boolean => {
    const rel = path.relative(ctx.projectRoot, path.resolve(absPath));
    if (rel.startsWith('..')) {
      return false;
    }
    const relPosix = rel.split(path.sep).join('/');
    return sourceGlobs.some((g) => g.match(relPosix));
  };

  const i18n: MochiI18nWatchHook = {
    kind(absPath) {
      // Source globs win over `localesDir` so a watched component that happens
      // to live under the locales dir still extracts; in practice they're
      // disjoint (components vs `.po`/generated artifacts).
      if (isSourcePath(absPath)) {
        return 'source';
      }
      return isCatalogPath(absPath) ? 'catalog' : null;
    },
    async handleChange(absPath) {
      const abs = path.resolve(absPath);
      const read = () => Bun.file(abs).text();
      if (isSourcePath(abs)) {
        // A watched i18n component changed. Re-extract across the adapters'
        // source files and persist the updated `.po` catalogs (`directVisit`
        // saves + compiles). Then re-read them into the build-mode `hub` so its
        // message index matches the catalogs the SSR/client bundles will embed
        // when we rebuild below. Without an extract hub (production) there is
        // nothing to do here.
        if (!extractHub) {
          return false;
        }
        await extractHub.directVisit(false, false, true);
        await hub.onFileChange(sourcePoPath, () => Bun.file(sourcePoPath).text());
        return true;
      }
      // A catalog file (`.po`) or generated artifact changed. `onFileChange`
      // re-reads the catalog and recompiles it to disk, returning the set of
      // invalidated compiled modules.
      const info = await hub.onFileChange(abs, read);
      // `undefined` → `config.dev` is off; `sourceTriggered` → this write came
      // from our own extraction (avoid a reload loop); empty `invalidate` →
      // a confUpdate / compiled-catalog self-write that needs no page reload.
      if (!info || info.sourceTriggered || info.invalidate.size === 0) {
        return false;
      }
      return true;
    },
  };

  return { handle, i18n };
}
