import path from 'node:path';
import type { PreprocessorGroup } from 'svelte/compiler';
import type { MochiI18nOptions } from '../types';
import type { Handle } from '../hooks';
import { getFilter, setFilter } from '../extensions';
import { logger } from '../log';

/**
 * The client loader: registers a reactive ($state) runtime collection and
 * loads the active locale synchronously at import time, so hydrated islands
 * render the correct strings with no async flash. `setLocale()` switches the
 * locale in place (all locales are bundled via the sync proxy).
 */
function clientLoaderSource(key: string, sourceLocale: string): string {
  return `// Generated by mochi-framework i18n (Wuchale). Edit your components / wuchale.config.js instead.
import { registerLoaders, loadLocaleSync, defaultCollection } from 'wuchale/load-utils';
import { loadCatalog, loadCount } from './.wuchale/${key}.proxy.sync.js';

const runtimes = $state([]);

export const getRuntime = registerLoaders('${key}', loadCatalog, loadCount, defaultCollection(runtimes));
export const getRuntimeRx = getRuntime;

/** Switch locale in place — instant, no reload. */
export function setLocale(locale) {
  loadLocaleSync(locale);
}

loadLocaleSync(globalThis.__mochi_locale__ ?? '${sourceLocale}');
`;
}

/**
 * The server loader: reads the active locale from Mochi's globally-pinned
 * request context (set by the i18n middleware). This deliberately avoids
 * Wuchale's own AsyncLocalStorage, which would not survive Mochi's
 * per-component SSR bundling.
 */
function serverLoaderSource(key: string, sourceLocale: string): string {
  return `// Generated by mochi-framework i18n (Wuchale). Reads the active locale from the Mochi request context.
import { getRequestContext } from 'mochi-framework';
import toRuntime from 'wuchale/runtime';
import { loadCatalog } from './.wuchale/${key}.proxy.sync.js';

const cache = {};

function get(loadID = 0) {
  const locale = getRequestContext().locals.locale ?? '${sourceLocale}';
  const byLocale = (cache[locale] ??= {});
  return (byLocale[loadID] ??= toRuntime(loadCatalog(loadID, locale), locale));
}

export const getRuntime = get;
export const getRuntimeRx = get;
`;
}

async function writeIfChanged(filePath: string, contents: string): Promise<void> {
  const file = Bun.file(filePath);
  if ((await file.exists()) && (await file.text()) === contents) {
    return;
  }
  await Bun.write(filePath, contents);
}

/**
 * Seed the active locale into the page `<head>` as `window.__mochi_locale__`
 * so the client loader can load the matching catalog before islands hydrate.
 */
function seedLocale(html: string, locale: string): string {
  const value = JSON.stringify(locale).replace(/</g, '\\u003C');
  const tag = `<script>window.__mochi_locale__=${value}</script>`;
  return html.includes('<head>') ? html.replace('<head>', `<head>${tag}`) : tag + html;
}

/**
 * Wire Wuchale into Mochi. Loads the Wuchale config, generates the Mochi-aware
 * loaders, creates a Wuchale `Hub` (one adapter handler per adapter, shared
 * message index), composes the compile-time transform into the
 * `compile:preprocessors` filter, and returns the per-request locale
 * middleware.
 */
export async function setupWuchaleI18n(options: MochiI18nOptions, ctx: { development: boolean; projectRoot: string }): Promise<Handle> {
  const sourceLocale = options.sourceLocale ?? options.locales[0] ?? 'en';
  const configPath = path.resolve(ctx.projectRoot, options.config ?? './wuchale.config.js');

  let wuchale: typeof import('wuchale');
  try {
    wuchale = await import('wuchale');
  } catch {
    throw new Error("Mochi i18n requires the 'wuchale' package. Install it with `bun add wuchale @wuchale/svelte`.");
  }
  const { getConfig, Hub } = wuchale;

  const config = await getConfig(configPath);

  // Write the Mochi-aware loaders before creating the Hub so Wuchale's
  // getLoaderPath() detects the separate server/client `.svelte.js` pair.
  // Wuchale never overwrites them because the adapters use `loader: 'custom'`.
  const localesDir = path.resolve(ctx.projectRoot, config.localesDir);
  for (const key of Object.keys(config.adapters)) {
    await writeIfChanged(path.join(localesDir, `${key}.loader.svelte.js`), clientLoaderSource(key, sourceLocale));
    await writeIfChanged(path.join(localesDir, `${key}.loader.server.svelte.js`), serverLoaderSource(key, sourceLocale));
  }

  // 'build' mode: the per-file transform is always active and transform-only,
  // using the message index seeded from the committed catalogs. Run the
  // `wuchale` CLI (or `bun run extract`) to (re)extract after adding strings.
  const hub = await Hub.create('build', () => config, ctx.projectRoot);

  // Compose the Wuchale transform into the compile:preprocessors filter,
  // preserving any user-provided filter. The Hub routes each file to the
  // matching adapter (or returns no output for non-i18n files).
  const prev = getFilter('compile:preprocessors');
  setFilter('compile:preprocessors', (value, fctx) => {
    const base = prev ? prev(value, fctx) : value;
    const forServer = fctx.target === 'server';
    const wuchalePreprocessor: PreprocessorGroup = {
      name: 'wuchale',
      async markup({ content, filename }) {
        const [out] = await hub.transform(content, filename ?? fctx.filename, forServer);
        return out.code != null ? { code: out.code } : undefined;
      },
    };
    return [wuchalePreprocessor, ...base];
  });

  logger.info(`i18n: wuchale ready — locales [${options.locales.join(', ')}], source '${sourceLocale}'`);

  return async ({ event, resolve }) => {
    // Locale resolution is only meaningful for page/api requests, which run
    // inside the request context. Assets, fallback and error responses run
    // outside it (so `getRequestContext()` would throw) and never need a locale.
    if (event.kind !== 'page' && event.kind !== 'api') {
      return resolve(event);
    }
    const locale = options.resolveLocale(event) ?? sourceLocale;
    event.locals.locale = locale;
    return resolve(event, { transformPage: ({ html }) => seedLocale(html, locale) });
  };
}
