import { Mochi, sequence, silenceInternalRoutes } from 'mochi-framework';
import { rateLimit } from './lib/rateLimit';
import { authGuard } from './lib/auth.server';
import { runMigrations } from './lib/db.server';
import { routes } from './routes';

// Tailwind: build-time CSS is generated by scripts/prebuild.ts. In dev we attach
// the watcher, dynamically imported so production never loads @tailwindcss/oxide's
// native binding. See packages/docs/175-tailwind.md.
if (process.env.MODE === 'development') {
  const { setupTailwind } = await import('mochi-framework/tailwind');
  await setupTailwind({
    input: './src/styles/app.css',
    output: './src/styles/app.generated.css',
    minify: false,
  });
}

// STUB: apply pending SQL migrations on boot (no-op until the migration runner
// and bun:sqlite are wired in). See tasks/migrations.md.
runMigrations();

const PORT = Number(process.env.PORT) || 3338;

await Mochi.serve({
  port: PORT,
  development: process.env.MODE === 'development',
  htmlShell: './src/shell.html',
  trailingSlash: 'always',
  // rateLimit is a pass-through stub; authGuard lets everything through for now.
  handle: sequence(rateLimit({ max: 5, windowMs: 60_000, paths: ['/login'] }), authGuard),
  filters: {
    'consoleLogger:line': silenceInternalRoutes,
  },
  routes,
});

console.log('Server running at http://localhost:' + PORT);
