import mitt, { type Emitter, type Handler } from 'mitt';
import { pinGlobal } from './globalState';

export type MochiRequestKind = 'page' | 'api' | 'file' | 'asset' | 'fallback' | 'error';

export interface MochiRequestEvent {
  /**
   * Per-request correlation id. Stable across `request`, `error`,
   * `action:invoke`, and `action:complete` for the same HTTP request.
   * Framework-generated by default. To honour an upstream id (e.g. from a
   * trusted reverse proxy), set `proxy.requestIdHeader` on
   * `Mochi.serve()`. Also exposed via `getRequestContext().requestId`.
   */
  requestId: string;
  kind: MochiRequestKind;
  method: string;
  path: string;
  status: number;
  duration: number;
  /** True when the request was issued by route warmup, not a real client. */
  warmup?: boolean;
}

export interface MochiWsOpenEvent {
  path: string;
  duration: number;
}

export interface MochiWsCloseEvent {
  path: string;
  duration: number;
  code: number;
  reason: string;
}

export interface MochiWsMessageEvent {
  path: string;
  size: number;
  type: 'text' | 'binary';
}

export interface MochiSseOpenEvent {
  path: string;
}

export interface MochiSseCloseEvent {
  path: string;
  duration: number;
}

export interface MochiSseMessageEvent {
  path: string;
  size: number;
  event?: string;
}

export type MochiFileChangeType = 'add' | 'change' | 'unlink' | 'addDir' | 'unlinkDir';

export interface MochiFileChangeEvent {
  /** Absolute path of the changed file, as reported by the dev watcher. */
  path: string;
  /** Kind of change, mirroring chokidar event names. */
  type: MochiFileChangeType;
}

export type MochiIslandErrorKind = 'hydratable' | 'server' | 'client-hydrate';

export interface MochiIslandErrorEvent {
  componentName: string;
  islandId: string | undefined;
  kind: MochiIslandErrorKind;
  message: string;
  /** Stack trace — populated only in development builds. */
  stack?: string;
}

export type MochiCacheStatus = 'fresh' | 'stale' | 'expired' | 'miss';

export interface MochiCacheReadEvent {
  key: string;
  status: MochiCacheStatus;
}

export interface MochiCacheRevalidateEvent {
  key: string;
}

export interface MochiCacheRevalidateFailedEvent {
  key: string;
  /** The error thrown by the background revalidation function. */
  error: unknown;
}

export interface MochiCacheErrorEvent {
  key: string;
  /** Which storage operation threw. */
  operation: 'get' | 'set' | 'remove';
  error: unknown;
}

export interface MochiServerStartEvent {
  /** Bound TCP port; absent when serving over a Unix socket. */
  port?: number;
  hostname?: string;
  development: boolean;
  routes: { page: number; api: number; ws: number; sse: number; file: number };
}

export interface MochiServerStopEvent {
  reason: 'signal';
  signal?: 'SIGTERM' | 'SIGINT';
}

export interface MochiWarmupStartEvent {
  /** Static page routes about to be warmed (no `:param` or `*` segments). */
  routeCount: number;
}

export interface MochiWarmupCompleteEvent {
  /** Static page routes that were warmed (no `:param` or `*` segments). */
  routeCount: number;
  /** How many warmup invocations threw or returned a 5xx response. */
  errorCount: number;
  /** Wall-clock time for the whole warmup batch (ms). */
  durationMs: number;
}

export type MochiErrorKind = 'page' | 'api' | 'action' | 'file';

export interface MochiErrorEvent {
  /** Same `requestId` as the surrounding `request` event. */
  requestId: string;
  kind: MochiErrorKind;
  path: string;
  method: string;
  status: number;
  message: string;
  /** Stack trace — populated only in development builds. */
  stack?: string;
  /** Form action name — present only when `kind === 'action'`. */
  actionName?: string;
}

export type MochiActionResult = 'success' | 'fail' | 'redirect' | 'error';

export interface MochiActionInvokeEvent {
  /** Same `requestId` as the surrounding `request` event. */
  requestId: string;
  path: string;
  actionName: string;
}

export interface MochiActionCompleteEvent {
  /** Same `requestId` as the matching `action:invoke`. */
  requestId: string;
  path: string;
  actionName: string;
  result: MochiActionResult;
  /** HTTP status — set for `fail` and `redirect`; absent for `success` and `error` (the `error` event carries the status). */
  status?: number;
}

export interface MochiCompileStartEvent {
  /** Absolute path of the `.svelte` file about to be compiled. */
  path: string;
}

export interface MochiCompileCompleteEvent {
  /** Absolute path of the compiled `.svelte` file. */
  path: string;
  ssrSizeBytes: number;
  hydratableCount: number;
  serverIslandCount: number;
  /** Wall-clock time spent inside `ComponentRegistry.compile()`. */
  durationMs: number;
}

export type MochiRecompileTrigger = 'file' | 'css' | 'svelte-config' | 'html-shell' | 'entry';

export interface MochiRecompileStartEvent {
  trigger: MochiRecompileTrigger;
  /** Path of the file whose change triggered the rebuild. */
  path: string;
  /** Pages about to be recompiled. `0` for the CSS fast-path. */
  pageCount: number;
}

export interface MochiRecompileCompleteEvent {
  trigger: MochiRecompileTrigger;
  path: string;
  pageCount: number;
  /** Absolute paths of the page entries that were recompiled this cycle. */
  pages: string[];
  /** Number of `buildClientBundle()` calls that ran during this cycle. */
  clientBundleCount: number;
  durationMs: number;
}

export interface MochiClientBundleEvent {
  /** Entrypoints fed to `Bun.build` (HydratableIsland + per-component virtuals). */
  entryCount: number;
  /** Sum of output sizes (JS + CSS) reported by Bun's metafile. */
  outputBytes: number;
  durationMs: number;
}

export interface MochiCompileBatchCompleteEvent {
  /** Number of `.svelte` files compiled in this batch. */
  count: number;
  /** Wall-clock time for the entire batch (Bun.build + post-build processing). */
  durationMs: number;
}

export interface MochiPreprocessCacheEvent {
  /** Absolute path of the `.svelte` file the cache wrapper was invoked for. */
  filePath: string;
}

export interface MochiPreprocessCacheSummaryEvent {
  hits: number;
  misses: number;
  /** Total file lookups during the batch (`hits + misses`). */
  files: number;
}

export interface MochiCompileErrorLog {
  file?: string;
  line?: number;
  column?: number;
  message: string;
}

export interface MochiCompileErrorEvent {
  /** Absolute path of the `.svelte` file that failed to build. */
  path: string;
  message: string;
  logs: MochiCompileErrorLog[];
}

export type MochiEventMap = {
  request: MochiRequestEvent;
  'ws:open': MochiWsOpenEvent;
  'ws:message': MochiWsMessageEvent;
  'ws:close': MochiWsCloseEvent;
  'sse:open': MochiSseOpenEvent;
  'sse:message': MochiSseMessageEvent;
  'sse:close': MochiSseCloseEvent;
  'file:change': MochiFileChangeEvent;
  'island:error': MochiIslandErrorEvent;
  'cache:read': MochiCacheReadEvent;
  'cache:revalidate': MochiCacheRevalidateEvent;
  'cache:revalidate:failed': MochiCacheRevalidateFailedEvent;
  'cache:error': MochiCacheErrorEvent;
  'server:start': MochiServerStartEvent;
  'server:stop': MochiServerStopEvent;
  'warmup:start': MochiWarmupStartEvent;
  'warmup:complete': MochiWarmupCompleteEvent;
  error: MochiErrorEvent;
  'action:invoke': MochiActionInvokeEvent;
  'action:complete': MochiActionCompleteEvent;
  'compile:start': MochiCompileStartEvent;
  'compile:complete': MochiCompileCompleteEvent;
  'compile:batch-complete': MochiCompileBatchCompleteEvent;
  'compile:error': MochiCompileErrorEvent;
  'preprocess-cache:hit': MochiPreprocessCacheEvent;
  'preprocess-cache:miss': MochiPreprocessCacheEvent;
  'preprocess-cache:summary': MochiPreprocessCacheSummaryEvent;
  'recompile:start': MochiRecompileStartEvent;
  'recompile:complete': MochiRecompileCompleteEvent;
  'client-bundle:complete': MochiClientBundleEvent;
};

export interface MochiEmitter extends Emitter<MochiEventMap> {
  /**
   * Register `handler` under `name`, replacing any handler previously registered
   * under the same name (across any event type). Prefer this over `.on()` when
   * subscribing from a module that may be bundled into an SSR island — the dev
   * compile cache re-imports those bundles on every `.svelte` change, and naive
   * `.on()` calls pile up one subscriber per re-import.
   *
   * Namespace `name` to avoid collisions with unrelated subsystems (e.g.
   * `"docs:cache-clear"`, not `"cache-clear"`); two callers picking the same
   * name will silently evict each other.
   *
   * Don't mix this with `.off()` for the same name — the name table is
   * maintained only by `setHandler`, so calling `.off()` directly leaves a
   * stale entry that the next `setHandler(name, ...)` will try (harmlessly) to
   * re-remove from mitt.
   */
  setHandler<K extends keyof MochiEventMap>(name: string, type: K, handler: (event: MochiEventMap[K]) => void): void;
}

// TODO: Check if this is still needed since we fixed the bundling duplication
// Use a global singleton so that the main server runtime and any bundled
// SSR/client copy of this module share the same emitter instance. Without
// this, Bun's bundler creates a separate `mitt()` in each compiled bundle,
// and subscribers registered via one copy never see events emitted by the
// other. Mirrors the pattern used for `requestContext` in `requestContext.ts`.
export const mochiEvents: MochiEmitter = pinGlobal<MochiEmitter>('__mochi_events__', () => {
  const base = mitt<MochiEventMap>() as MochiEmitter;
  const byName = new Map<string, { type: keyof MochiEventMap; handler: Handler<MochiEventMap[keyof MochiEventMap]> }>();
  base.setHandler = (name, type, handler) => {
    const prior = byName.get(name);
    if (prior) {
      // mitt's off() is generic per-event-type; we erased that K when storing
      // the handler in the name table, so cast it back here to satisfy off().
      base.off(prior.type, prior.handler as never);
    }
    byName.set(name, {
      type,
      handler: handler as Handler<MochiEventMap[keyof MochiEventMap]>,
    });
    base.on(type, handler);
  };
  return base;
});

/**
 * `true` when at least one handler is registered for `name`. Use this to skip
 * payload construction for events whose payload is non-trivial to build:
 *
 * ```ts
 * if (hasSubscribers('compile:error')) {
 *   mochiEvents.emit('compile:error', { ...buildLogs(...) });
 * }
 * ```
 *
 * Cheap, synchronous; prefer it over emitting unconditionally when the
 * payload involves loops, allocations, or stack capture.
 */
export function hasSubscribers(name: keyof MochiEventMap): boolean {
  return (mochiEvents.all.get(name)?.length ?? 0) > 0;
}
