import { AsyncLocalStorage } from 'node:async_hooks';
import type { MochiCookieJar } from './cookies';
import type { MochiFormResult } from './types';
import { pinGlobal } from './globalState';

export interface MochiRequestContext {
  /**
   * Stable correlation id for this HTTP request. Framework-generated by
   * default; reads from an upstream header when `proxy.requestIdHeader` is
   * configured on `Mochi.serve()`. Carried on every lifecycle event for the
   * request (`request`, `error`, `action:invoke`, `action:complete`) so
   * observability tooling can stitch events together.
   */
  requestId: string;
  /** The incoming HTTP request. */
  request: Request;
  /** Parsed URL of the request. */
  url: URL;
  /** Route parameters extracted by Bun's router (e.g. { id: "123" } for /item/:id). */
  params: Record<string, string>;
  /** Per-request data set by middleware. */
  locals: Record<string, unknown>;
  /**
   * `true` when this request was issued by route warmup at startup rather than
   * a real client. Use it to skip side effects (server-side counters,
   * analytics, rate-limit priming) in `serverProps` or components that
   * shouldn't fire for synthetic warmup hits.
   */
  isWarmup: boolean;
  /** Cookie jar for reading/writing cookies within this request. */
  cookies: MochiCookieJar;
  /**
   * Per-request hydratable-island props dedup registry, keyed by serialized
   * JSON payload, valued by ref id (e.g. "mochi-props-3"). Populated by
   * `emitIslandProps()` during SSR; consumed by `ComponentRegistry` to hoist
   * shared `<script type="application/json">` blocks into the rendered HTML.
   * Internal — not for application use.
   */
  islandProps: Map<string, string>;
  /**
   * Dev-only debug-bar data bag. Populated during routing (route/pathname/
   * params) and SSR (e.g. `emitIslandProps()` fills `islandProps`).
   * Snapshotted onto `RenderResult.debugBarData` at end of render and
   * surfaced to the client via `window.__mochi_debug`. Undefined in
   * production so the record path stays zero-cost. Add new keys here as
   * more debug data is captured.
   */
  debugBarData?: DebugBarData;
  /**
   * Result of the form action that just ran, available during POST re-renders
   * of an entry route with `actions`. `null` or omitted on plain GET requests.
   */
  form?: MochiFormResult;
  /**
   * Returns the client's IP address, or `null` when no source is available.
   *
   * By default this is Bun's connecting `remoteAddress`. Behind a reverse
   * proxy, configure `Mochi.serve({ proxy: { addressHeader: '...' } })` to
   * read it from a forwarded header instead. For `'x-forwarded-for'`,
   * `proxy.xffDepth` controls how many trusted proxies sit in front of the
   * server; the address is read from the right to block spoofing.
   */
  getClientAddress: () => string | null;
}

export interface BundleInfo {
  url: string;
  label: string;
  sizeBytes: number;
  kind: 'bootstrap' | 'island' | 'chunk';
  inputs: Array<{ path: string; size: number }>;
}

/**
 * SSR-side debug-bar payload. These fields are emitted into the cached HTML
 * body and stay stable across cache hits. The dynamic per-request fields
 * (`headers`, `requestCookies`) are not on this shape — they're injected
 * client-side by `appendDebugTail`'s trailing `<script>` and only appear on
 * `window.__mochi_debug` at runtime (see `DebugBarRuntimeData`).
 */
export interface DebugBarData {
  /** Route pattern that matched (e.g. "/docs/:slug"). */
  route: string;
  /** Concrete request pathname (e.g. "/docs/intro"). */
  pathname: string;
  /** Route params extracted from the pattern. */
  params: Record<string, string>;
  /** islandId → pretty-printed props JSON. */
  islandProps: Record<string, string>;
  /**
   * Always `true` in dev while the page-cache feature is being rebuilt; the
   * `/__mochi/admin/page-cache` route serves placeholder data. The debug bar
   * reads this to decide whether to show its Cache panel button.
   */
  pageCacheEnabled?: boolean;
  /**
   * Cookie names that partition the cache key for this route. Currently always
   * empty while the page cache is being rebuilt; the Request panel still reads
   * this to flag cookie rows.
   */
  varyOnCookies?: string[];
  /** Whether live-reload is enabled for this server instance. */
  liveReloadEnabled?: boolean;
  /** Time in milliseconds the SSR render took (compile check + Svelte render + HTML processing). */
  ssrDurationMs?: number;
  /** Framework JS bundles injected for this page (bootstrap, island entries, shared chunks). */
  bundles?: BundleInfo[];
  /** Mochi framework version (constant per server). */
  mochiVersion?: string;
  /** Resolved Svelte version (constant per server). */
  svelteVersion?: string;
  /** Bun runtime version (constant per server). */
  bunVersion?: string;
  /** Curated snapshot of the `Mochi.serve()` configuration (constant per server). */
  config?: DebugBarConfig;
}

/**
 * Serializable, descriptive subset of `MochiServeOptions` surfaced in the debug
 * bar's Info panel. Functions (handle, routes, fetch) are reduced to booleans or
 * counts so the whole shape survives `JSON.stringify` into the HTML.
 */
export interface DebugBarConfig {
  mode: 'development' | 'production';
  port?: number;
  hostname?: string;
  debugBar: boolean;
  liveReload: boolean;
  warmup: boolean;
  compressServerIslandProps: boolean;
  trailingSlash: 'never' | 'always';
  assetPrefix?: string;
  logLevel: string;
  /** Whether an `options.handle` middleware is configured. */
  middleware: boolean;
  csrf: boolean;
  proxy: boolean;
  markdown: boolean;
  routeCount: number;
}

/**
 * Shape of `window.__mochi_debug` once the trailing tail script has run.
 * Extends the SSR shape with the per-request fields populated client-side.
 */
export interface DebugBarRuntimeData extends DebugBarData {
  /** Outgoing response headers as `[name, value]` pairs (preserves duplicate Set-Cookie entries). */
  headers?: Array<[string, string]>;
  /** `[name, value]` pairs of cookies sent on the inbound request. */
  requestCookies?: Array<[string, string]>;
}

// TODO: Review this for cross-request security
// Use a global singleton so that both Mochi.ts (which calls .run()) and
// compiled SSR components (which call .getStore()) share the same instance.
// Without this, Bun's bundler creates a separate copy of the AsyncLocalStorage
// in each compiled component, breaking the context chain.
export const requestContext = pinGlobal('__mochi_request_context__', () => new AsyncLocalStorage<MochiRequestContext>());

/**
 * Returns the current request context. Available in any server-side code
 * running within a request (components, API handlers, helpers).
 *
 * ```svelte
 * <script>
 *   import { getRequestContext } from "mochi-framework";
 *   const { params, locals, url } = getRequestContext();
 * </script>
 * ```
 */
export function getRequestContext(): MochiRequestContext {
  const ctx = requestContext.getStore();
  if (!ctx) {
    throw new Error('getRequestContext() called outside of a request. ' + 'It is only available in server-side code running within a Mochi request handler.');
  }
  return ctx;
}
