// Generated by mochi-framework i18n (Wuchale). Edit your components / wuchale.config.js instead.
import { registerLoaders, loadLocaleSync, defaultCollection } from 'wuchale/load-utils';
import { loadCatalog, loadCount } from './.wuchale/main.proxy.sync.js';

const runtimes = $state([]);

export const getRuntime = registerLoaders('main', loadCatalog, loadCount, defaultCollection(runtimes));
export const getRuntimeRx = getRuntime;

/** Switch locale in place — instant, no reload. */
export function setLocale(locale) {
  loadLocaleSync(locale);
}

loadLocaleSync(globalThis.__mochi_locale__ ?? 'en');
