import path from 'node:path';
import { fileURLToPath } from 'node:url';
import slugify from 'slugify';
import { loadDocs } from './docs';

const OUT_PATH = path.resolve(path.dirname(fileURLToPath(import.meta.url)), 'docComponents.generated.ts');

function toIdentifier(slug: string): string {
  const safe = slugify(slug, { replacement: '_', strict: true, lower: false });
  return `Doc_${/^\d/.test(safe) ? `_${safe}` : safe}`;
}

export async function generateDocsBarrel(): Promise<void> {
  const docs = await loadDocs();

  const lines: string[] = [];
  lines.push('// AUTO-GENERATED by generateDocsBarrel.ts — do not edit.');
  lines.push('');
  for (const doc of docs) {
    lines.push(`import ${toIdentifier(doc.slug)} from '../../../docs/${doc.filename}';`);
  }
  lines.push('');
  const firstDoc = docs[0];
  if (firstDoc) {
    lines.push(`export type DocComponent = typeof ${toIdentifier(firstDoc.slug)};`);
  } else {
    lines.push('export type DocComponent = unknown;');
  }
  lines.push('');
  lines.push('export const docComponents: Record<string, DocComponent> = {');
  for (const doc of docs) {
    lines.push(`  ${JSON.stringify(doc.slug)}: ${toIdentifier(doc.slug)},`);
  }
  lines.push('};');
  lines.push('');

  const content = lines.join('\n');

  const existing = await Bun.file(OUT_PATH)
    .text()
    .catch(() => null);
  if (existing === content) {
    return;
  }
  try {
    await Bun.write(OUT_PATH, content);
  } catch (err) {
    // The barrel is a generated dev convenience; if the write fails (e.g. a read-only or
    // foreign-owned filesystem in a deployed container) but a usable file already exists,
    // warn and keep running instead of taking the server down — only a genuinely missing
    // barrel is fatal.
    if (existing === null) {
      throw err;
    }
    console.warn(`generateDocsBarrel: could not rewrite ${OUT_PATH}, keeping existing file:`, err);
  }
}

if (import.meta.main) {
  await generateDocsBarrel();
}
