import path from 'node:path';
import { fileURLToPath } from 'node:url';
import slugify from 'slugify';
import { loadPosts } from './blog';

const OUT_PATH = path.resolve(path.dirname(fileURLToPath(import.meta.url)), 'blogComponents.generated.ts');

function toIdentifier(slug: string): string {
  const safe = slugify(slug, { replacement: '_', strict: true, lower: false });
  return `Post_${/^\d/.test(safe) ? `_${safe}` : safe}`;
}

export async function generateBlogBarrel(): Promise<void> {
  // Drafts are included so the barrel is identical in dev and prod; the runtime
  // (loadPosts/getPost) is what keeps drafts out of production responses.
  const posts = await loadPosts({ includeDrafts: true });

  const lines: string[] = [];
  lines.push('// AUTO-GENERATED by generateBlogBarrel.ts — do not edit.');
  lines.push('');
  for (const post of posts) {
    lines.push(`import ${toIdentifier(post.slug)} from '../blog/${post.filename}';`);
  }
  lines.push('');
  const firstPost = posts[0];
  if (firstPost) {
    lines.push(`export type PostComponent = typeof ${toIdentifier(firstPost.slug)};`);
  } else {
    lines.push('export type PostComponent = unknown;');
  }
  lines.push('');
  lines.push('export const blogComponents: Record<string, PostComponent> = {');
  for (const post of posts) {
    lines.push(`  ${JSON.stringify(post.slug)}: ${toIdentifier(post.slug)},`);
  }
  lines.push('};');
  lines.push('');

  const content = lines.join('\n');

  const existing = await Bun.file(OUT_PATH)
    .text()
    .catch(() => null);
  if (existing === content) {
    return;
  }
  try {
    await Bun.write(OUT_PATH, content);
  } catch (err) {
    // Same recovery as generateDocsBarrel: on a read-only filesystem a stale-but-usable
    // barrel beats taking the server down; only a genuinely missing barrel is fatal.
    if (existing === null) {
      throw err;
    }
    console.warn(`generateBlogBarrel: could not rewrite ${OUT_PATH}, keeping existing file:`, err);
  }
}

if (import.meta.main) {
  await generateBlogBarrel();
}
