import { styleText } from 'node:util';

type Args = {
  base: string;
  concurrency: number;
};

const usage = `Usage: bun run check-llms [base] [--concurrency N]

Verifies every llms.txt surface the site exposes: the aggregate endpoints
(/llms.txt, /llms-recommended.txt, /llms-full.txt, /llms.json, /SKILL.md), one
per doc, and one per demo.

The expected set is derived from <base>/sitemap.xml, NOT from /llms.json — the
sitemap lists every page the site serves, while /llms.json is generated by the
same registry that generates the llms.txt routes. Checking the registry against
itself is how a demo can drop out of both and still look healthy; the sitemap is
the independent witness. The two lists are diffed, then every URL in the union
is fetched and its body sanity-checked.

The sitemap hardcodes the production origin, so each <loc> is re-pointed at
<base> — pass a local origin to check a dev server.

Arguments:
  base             Origin to check (default: https://mochi.fast)
  --concurrency N  Max simultaneous fetches (default: 12)

Exits 1 if any llms.txt is unregistered, broken or suspect, 2 on a setup problem.`;

const parseArgs = (argv: string[]): Args => {
  const positional: string[] = [];
  let concurrency = 12;
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '-h' || a === '--help') {
      console.log(usage);
      process.exit(0);
    } else if (a === '--concurrency') {
      const next = argv[++i];
      if (!next) {
        console.error('Missing value for --concurrency');
        process.exit(2);
      }
      concurrency = Number(next);
    } else if (a.startsWith('--')) {
      console.error(`Unknown flag: ${a}`);
      process.exit(2);
    } else {
      positional.push(a);
    }
  }
  if (!Number.isFinite(concurrency) || concurrency < 1) {
    console.error('--concurrency must be a positive number');
    process.exit(2);
  }
  const base = (positional[0] ?? 'https://mochi.fast').replace(/\/+$/, '');
  if (!URL.canParse(base) || !['http:', 'https:'].includes(new URL(base).protocol)) {
    console.error(`base must be an http(s) origin, got: ${base}`);
    process.exit(2);
  }
  return { base, concurrency };
};

/** Run thunks with a bounded number in flight at once. */
async function pool<T>(items: T[], limit: number, fn: (item: T) => Promise<void>): Promise<void> {
  let cursor = 0;
  const workers = Array.from({ length: Math.min(limit, items.length) }, async () => {
    while (cursor < items.length) {
      const item = items[cursor++];
      await fn(item);
    }
  });
  await Promise.all(workers);
}

const decodeXmlEntities = (s: string) =>
  s
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&amp;/g, '&');

/** Re-point an absolute URL from the site's baked-in production origin at `base`. */
function rebase(url: string, base: string): string | null {
  let u: URL;
  try {
    u = new URL(url, `${base}/`);
  } catch {
    return null;
  }
  const origin = new URL(base);
  u.protocol = origin.protocol;
  u.host = origin.host;
  return u.toString();
}

async function fetchText(url: string): Promise<string> {
  let res: Response;
  try {
    res = await fetch(url);
  } catch (err) {
    console.error(styleText('red', `Could not reach ${url} — is the site up?`));
    console.error(String(err));
    process.exit(2);
  }
  if (!res.ok) {
    console.error(styleText('red', `GET ${url} → ${res.status}. Is the site up?`));
    process.exit(2);
  }
  return res.text();
}

interface LlmsIndexEntry {
  title: string;
  description: string;
  url: string;
}

type Kind = 'doc' | 'demo' | 'aggregate';

interface Expected {
  /** The llms.txt URL itself. */
  url: string;
  kind: Kind;
  /** Doc or demo slug; empty for aggregates. */
  slug: string;
  /** The page this source belongs to, for the failure message. */
  page: string;
}

/**
 * The llms.txt URL a sitemap page should expose, or null for pages that have
 * none by design (the home page and the blog). Demo paths track each demo's own
 * href rather than a /demos/ prefix, so they're derived from the page URL —
 * `/cookie-vary-test/` really does serve `/cookie-vary-test/llms.txt`.
 */
function expectedForPage(pageUrl: string): Expected | null {
  const { pathname } = new URL(pageUrl);
  if (pathname === '/' || pathname === '/blog/' || pathname.startsWith('/blog/')) {
    return null;
  }
  const withSlash = pathname.endsWith('/') ? pathname : `${pathname}/`;
  const slug = withSlash.slice(0, -1).split('/').pop() ?? '';
  const kind: Kind = pathname.startsWith('/docs/') ? 'doc' : 'demo';
  return { url: new URL(`${withSlash}llms.txt`, pageUrl).toString(), kind, slug, page: pageUrl };
}

const AGGREGATES = ['/llms.txt', '/llms-recommended.txt', '/llms-full.txt', '/llms.json', '/SKILL.md'];

interface Failure {
  url: string;
  detail: string;
}

async function main() {
  const { base, concurrency } = parseArgs(process.argv.slice(2));

  const sitemapXml = await fetchText(`${base}/sitemap.xml`);
  const pages: string[] = [];
  const locRe = /<loc>\s*([\s\S]*?)\s*<\/loc>/gi;
  let m: RegExpExecArray | null;
  while ((m = locRe.exec(sitemapXml)) !== null) {
    const rebased = rebase(decodeXmlEntities(m[1]), base);
    if (rebased === null) {
      console.error(styleText('yellow', `Skipping unparseable <loc>: ${m[1]}`));
      continue;
    }
    pages.push(rebased);
  }
  if (pages.length === 0) {
    console.error(styleText('red', `No <loc> entries in ${base}/sitemap.xml`));
    process.exit(2);
  }

  const expected = new Map<string, Expected>();
  for (const page of pages) {
    const e = expectedForPage(page);
    if (e !== null) {
      expected.set(e.url, e);
    }
  }

  const indexJson: { docs: LlmsIndexEntry[]; demos: LlmsIndexEntry[] } = JSON.parse(await fetchText(`${base}/llms.json`));
  const declared = new Map<string, Kind>();
  for (const [kind, entries] of [
    ['doc', indexJson.docs],
    ['demo', indexJson.demos],
  ] as const) {
    for (const entry of entries ?? []) {
      const url = rebase(entry.url, base);
      if (url !== null) {
        declared.set(url, kind);
      }
    }
  }

  console.log(styleText('dim', `${pages.length} pages in sitemap.xml, ${declared.size} sources in llms.json — checking ${base} …\n`));

  // A page the site serves whose llms.txt the registry never declared. This is
  // the regression the sitemap cross-check exists for: the route is generated
  // from the registry, so an unregistered demo has no route at all and 404s.
  const unregistered: Failure[] = [];
  for (const e of expected.values()) {
    if (!declared.has(e.url)) {
      unregistered.push({ url: e.url, detail: `${e.kind} '${e.slug}' is in sitemap.xml (${new URL(e.page).pathname}) but not in llms.json` });
    }
  }

  // The mirror image: a declared source whose page isn't served any more.
  const orphaned: Failure[] = [];
  const sitemapPaths = new Set(pages.map((p) => new URL(p).pathname));
  for (const url of declared.keys()) {
    const page = new URL(url).pathname.replace(/llms\.txt$/, '');
    if (!sitemapPaths.has(page)) {
      orphaned.push({ url, detail: `declared in llms.json but ${page} is not in sitemap.xml` });
    }
  }

  const targets = new Map<string, Expected>(expected);
  for (const [url, kind] of declared) {
    if (!targets.has(url)) {
      const slug =
        new URL(url).pathname
          .replace(/\/llms\.txt$/, '')
          .split('/')
          .pop() ?? '';
      targets.set(url, { url, kind, slug, page: '' });
    }
  }
  for (const path of AGGREGATES) {
    const url = `${base}${path}`;
    targets.set(url, { url, kind: 'aggregate', slug: path, page: '' });
  }

  const broken: Failure[] = [];
  const suspect: Failure[] = [];
  const bodies = new Map<string, string>();
  await pool([...targets.values()], concurrency, async (target) => {
    let res: Response;
    try {
      // Manual redirects: an llms.txt route must answer 200 directly. A hop here
      // means the trailing-slash policy no longer matches the registered path.
      res = await fetch(target.url, { redirect: 'manual' });
    } catch (err) {
      broken.push({ url: target.url, detail: err instanceof Error ? err.message : String(err) });
      return;
    }
    if (res.status >= 300 && res.status < 400) {
      broken.push({ url: target.url, detail: `${res.status} → ${res.headers.get('location') ?? '?'} (expected a direct 200)` });
      return;
    }
    if (!res.ok) {
      broken.push({ url: target.url, detail: String(res.status) });
      return;
    }

    const body = await res.text();
    bodies.set(target.url, body);
    const contentType = res.headers.get('content-type') ?? '';
    const isJson = target.url.endsWith('.json');
    const isMarkdown = target.url.endsWith('.md');
    if (isJson ? !contentType.includes('application/json') : !isMarkdown && !contentType.includes('text/plain')) {
      suspect.push({ url: target.url, detail: `content-type is '${contentType}'` });
    }
    if (body.trim().length === 0) {
      suspect.push({ url: target.url, detail: 'empty body' });
      return;
    }
    if (!isJson && body.trimStart().startsWith('<')) {
      suspect.push({ url: target.url, detail: 'body looks like HTML — an error page served with a 200?' });
      return;
    }
    if (target.kind === 'demo') {
      if (!body.startsWith(`## Demo: ${target.slug}`)) {
        suspect.push({ url: target.url, detail: `expected a '## Demo: ${target.slug}' header, got '${body.slice(0, 40).split('\n')[0]}'` });
      }
      // A files.ts path that doesn't exist on disk is only logged server-side and
      // silently dropped from the bundle, so count the fences that survived.
      const fences = (body.match(/^```/gm) ?? []).length;
      if (fences < 2) {
        suspect.push({ url: target.url, detail: 'no fenced source blocks — every declared file was dropped?' });
      }
    }
    if (target.kind === 'doc' && body.length < 100) {
      suspect.push({ url: target.url, detail: `only ${body.length} bytes` });
    }
  });

  // Every declared demo must also survive into the /llms-full.txt bundle, which
  // is built by a separate code path from the per-demo routes.
  const missingFromFull: Failure[] = [];
  const fullTxt = bodies.get(`${base}/llms-full.txt`);
  if (fullTxt !== undefined) {
    for (const [url, kind] of declared) {
      if (kind !== 'demo') {
        continue;
      }
      const slug =
        new URL(url).pathname
          .replace(/\/llms\.txt$/, '')
          .split('/')
          .pop() ?? '';
      if (!fullTxt.includes(`## Demo: ${slug}`)) {
        missingFromFull.push({ url, detail: `demo '${slug}' has no '## Demo: ${slug}' section in /llms-full.txt` });
      }
    }
  }

  // The /llms.txt index is what an agent actually reads to discover the rest.
  const missingFromIndex: Failure[] = [];
  const indexTxt = bodies.get(`${base}/llms.txt`);
  if (indexTxt !== undefined) {
    const listed = new Set<string>();
    const linkRe = /\]\((https?:\/\/[^)\s]+)\)/g;
    let link: RegExpExecArray | null;
    while ((link = linkRe.exec(indexTxt)) !== null) {
      const url = rebase(link[1], base);
      if (url !== null) {
        listed.add(url);
      }
    }
    for (const url of declared.keys()) {
      if (!listed.has(url)) {
        missingFromIndex.push({ url, detail: 'declared in llms.json but not linked from /llms.txt' });
      }
    }
  }

  const groups: { label: string; items: Failure[] }[] = [
    { label: `unregistered — page exists, llms.txt was never routed (this is a 404)`, items: unregistered },
    { label: `broken — llms.txt did not return 200`, items: broken },
    { label: `suspect — llms.txt returned 200 with a questionable body`, items: suspect },
    { label: `missing from /llms-full.txt`, items: missingFromFull },
    { label: `missing from the /llms.txt index`, items: missingFromIndex },
    { label: `orphaned — declared in llms.json with no page in sitemap.xml`, items: orphaned },
  ];

  const total = groups.reduce((sum, g) => sum + g.items.length, 0);
  if (total === 0) {
    console.log(styleText('green', `✓ All ${targets.size} llms.txt sources OK (${AGGREGATES.length} aggregate, ${declared.size} per-page).`));
    process.exit(0);
  }

  for (const group of groups) {
    if (group.items.length === 0) {
      continue;
    }
    console.log(styleText('red', `✗ ${group.items.length} ${group.label}:\n`));
    for (const f of group.items.sort((a, z) => a.url.localeCompare(z.url))) {
      console.log(`  ${styleText('bold', f.url)}`);
      console.log(styleText('dim', `      ${f.detail}`));
    }
    console.log('');
  }
  console.log(styleText('red', `${total} finding(s) across ${targets.size} checked sources.`));
  process.exit(1);
}

main();
