import { AsyncLocalStorage } from 'node:async_hooks';
import type { MochiCookieJar } from './cookies';
import type { IslandPropsEntry } from '../islands/islandPropsRegistry';
import type { MochiFormResult } from '../types';
import type { MochiRateLimitInfo } from './rateLimit';
import type { RequestCacheState } from './requestCache';
import { pinGlobal } from '../utils/globalState';

export interface MochiRequestContext {
  /**
   * Stable correlation id for this HTTP request. Framework-generated by
   * default; reads from an upstream header when `proxy.requestIdHeader` is
   * configured on `Mochi.serve()`. Carried on every lifecycle event for the
   * request (`request`, `error`, `action:invoke`, `action:complete`) so
   * observability tooling can stitch events together.
   */
  requestId: string;
  /** The incoming HTTP request. */
  request: Request;
  /** Parsed URL of the request. */
  url: URL;
  /** Route parameters extracted by Bun's router (e.g. { id: "123" } for /item/:id). */
  params: Record<string, string>;
  /** Per-request data set by middleware. */
  locals: Record<string, unknown>;
  /**
   * `true` when this request was issued by route warmup at startup rather than
   * a real client. Use it to skip side effects (server-side counters,
   * analytics, rate-limit priming) in `serverProps` or components that
   * shouldn't fire for synthetic warmup hits.
   */
  isWarmup: boolean;
  /** Cookie jar for reading/writing cookies within this request. */
  cookies: MochiCookieJar;
  /**
   * Hydratable-island props dedup registry, keyed by serialized JSON payload,
   * valued by ref id (e.g. "mochi-props-3") plus the number of islands that
   * emitted that exact payload. Populated by `emitIslandProps()` during SSR;
   * consumed by `ComponentRegistry`, which emits each payload as a
   * `<script type="application/json">` block before its first island and marks
   * blocks reused by >=2 islands with `data-shared` in the rendered HTML.
   * Effectively per-render scratch space: `renderComponent` clears it at the
   * start of every render, so sequential same-ctx renders (error page after a
   * failed render, an action re-render) don't clobber each other.
   * Internal — not for application use.
   */
  islandProps: Map<string, IslandPropsEntry>;
  /**
   * Backing store for the request-scoped cache (`requestCache()`,
   * `requestMemo()`, `getRequestCache()`), created on first use so requests that
   * never touch it allocate nothing. Entries die with the request, so an
   * invalidation between requests is still seen immediately.
   * Internal — application code goes through `getRequestCache()`.
   */
  requestCache?: RequestCacheState;
  /**
   * Dev-only debug-bar data bag. Populated during routing (route/pathname/
   * params) and SSR (e.g. `emitIslandProps()` fills `islandProps`).
   * Snapshotted onto `RenderResult.debugBarData` at end of render and
   * surfaced to the client via `window.__mochi_debug`. Undefined in
   * production so the record path stays zero-cost. Add new keys here as
   * more debug data is captured.
   */
  debugBarData?: DebugBarData;
  /**
   * Result of the form action that just ran, available during POST re-renders
   * of an entry route with `actions`. `null` or omitted on plain GET requests.
   */
  form?: MochiFormResult;
  /**
   * Returns the client's IP address, or `null` when no source is available.
   *
   * By default this is Bun's connecting `remoteAddress`. Behind a reverse
   * proxy, configure `Mochi.serve({ proxy: { addressHeader: '...' } })` to
   * read it from a forwarded header instead. For `'x-forwarded-for'`,
   * `proxy.xffDepth` controls how many trusted proxies sit in front of the
   * server; the address is read from the right to block spoofing.
   */
  getClientAddress: () => string | null;
  /**
   * Rate-limit state for this request when the matched route has a limiter and
   * the request was allowed: `limit`, `remaining`, `resetIn` (seconds),
   * `resetAt`, `key`, and `tier` when tiered. Undefined when no limiter applies,
   * on warmup requests, and when the limiter's `skip()` matched. Read it in
   * `serverProps` or server-side component code via
   * `getRequestContext().rateLimit` to render usage (e.g. "3 of 5 used").
   */
  rateLimit?: MochiRateLimitInfo;
}

export interface BundleInfo {
  url: string;
  label: string;
  sizeBytes: number;
  kind: 'bootstrap' | 'island' | 'chunk';
  inputs: Array<{ path: string; size: number }>;
}

/** One image produced during the request (dev debug bar only) — a signed
 * `getImageUrl()`/`<Image>` URL (`kind: 'url'`) or an inline `getImage()`
 * result (`kind: 'inline'`). */
export interface ImageDebugEntry {
  /** For `'inline'` entries this is a `data:` preview of the bytes (or empty when over the size cap); for `'url'` entries it's the served URL. */
  url: string;
  /** Stable identity for de-duping and list keying. Defaults to `url`; inline entries set their variant id so preview-less entries don't collide on an empty `url`. */
  id?: string;
  filename: string;
  /** The size's resolved, byte-affecting params — src, dimensions, format, quality (or `{ original: true }`). */
  params: Record<string, unknown>;
  /** Discriminates the deferred-URL path from the inline `getImage()` path. Defaults to `'url'`. */
  kind?: 'url' | 'inline';
  /** The named size applied, if any (absent for the full-size original). */
  size?: string;
  /** True when `src` resolves to a locally-imported asset (vs a remote URL). */
  local?: boolean;
  /** For local imports: the original file's project-relative path (dev only), so the
   * bar can show `src/…/hero.jpg` instead of the content-hashed served filename. */
  sourcePath?: string;
}

/**
 * SSR-side debug-bar payload. These fields are emitted into the cached HTML
 * body and stay stable across cache hits. The dynamic per-request fields
 * (`headers`, `requestCookies`) are not on this shape — they're injected
 * client-side by `appendDebugTail`'s trailing `<script>` and only appear on
 * `window.__mochi_debug` at runtime (see `DebugBarRuntimeData`).
 */
export interface DebugBarData {
  /** Route pattern that matched (e.g. "/docs/:slug"). */
  route: string;
  /** Concrete request pathname (e.g. "/docs/intro"). */
  pathname: string;
  /** Route params extracted from the pattern. */
  params: Record<string, string>;
  /**
   * Always `true` in dev while the page-cache feature is being rebuilt; the
   * `/__mochi/admin/page-cache` route serves placeholder data. The debug bar
   * reads this to decide whether to show its Cache panel button.
   */
  pageCacheEnabled?: boolean;
  /**
   * Cookie names that partition the cache key for this route. Currently always
   * empty while the page cache is being rebuilt; the Request panel still reads
   * this to flag cookie rows.
   */
  varyOnCookies?: string[];
  /** Whether live-reload is enabled for this server instance. */
  liveReloadEnabled?: boolean;
  /** Time in milliseconds the SSR render took (compile check + Svelte render + HTML processing). */
  ssrDurationMs?: number;
  /** Framework JS bundles injected for this page (bootstrap, island entries, shared chunks). */
  bundles?: BundleInfo[];
  /** Images produced via `getImageUrl()`/`<Image>`/`getImage()` during this request, with decoded params. */
  images?: ImageDebugEntry[];
  /** Request-scoped cache activity for this request (`requestCache()` / `requestMemo()`). */
  requestCache?: RequestCacheStats;
  /**
   * Server-island props recorded during SSR, keyed by the encrypted `signed-props`
   * token. Because island props are encrypted (opaque on the wire), the client
   * can't decode them; the debug bar reads the decoded snapshot from here instead,
   * matching on the token it sees in the island's `signed-props` attribute.
   */
  serverProps?: Record<string, string>;
  /** Mochi framework version (constant per server). */
  mochiVersion?: string;
  /** Resolved Svelte version (constant per server). */
  svelteVersion?: string;
  /** Bun runtime version (constant per server). */
  bunVersion?: string;
  /** Curated snapshot of the `Mochi.serve()` configuration (constant per server). */
  config?: DebugBarConfig;
}

/** Per-key hit/miss breakdown for the debug bar's expandable key list. */
export interface RequestCacheKeyStats {
  key: string;
  hits: number;
  misses: number;
}

/** Per-request cache counters shown in the debug bar's Cache panel. */
export interface RequestCacheStats {
  hits: number;
  misses: number;
  /** Entries still stored at the end of the render (rejected async entries evict themselves). */
  entries: number;
  /** Every key touched this request with its hit/miss tally, in first-touch order. */
  keys: RequestCacheKeyStats[];
}

/**
 * Serializable, descriptive subset of `MochiServeOptions` surfaced in the debug
 * bar's Info panel. Functions (handle, routes, fetch) are reduced to booleans or
 * counts so the whole shape survives `JSON.stringify` into the HTML.
 */
export interface DebugBarConfig {
  mode: 'development' | 'production';
  port?: number;
  hostname?: string;
  debugBar: boolean;
  liveReload: boolean;
  warmup: boolean;
  compressServerIslandProps: boolean;
  trailingSlash: 'never' | 'always';
  assetPrefix?: string;
  logLevel: string;
  /** Whether an `options.handle` middleware is configured. */
  middleware: boolean;
  csrf: boolean;
  proxy: boolean;
  markdown: boolean;
  /** Active email transport type. `dev` gates the toolbar's email-viewer link. */
  email: 'log' | 'dev' | 'smtp' | 'custom';
  routeCount: number;
}

/**
 * Shape of `window.__mochi_debug` once the trailing tail script has run.
 * Extends the SSR shape with the per-request fields populated client-side.
 */
export interface DebugBarRuntimeData extends DebugBarData {
  /** Outgoing response headers as `[name, value]` pairs (preserves duplicate Set-Cookie entries). */
  headers?: Array<[string, string]>;
  /** Names of cookies sent on the inbound request. Values are never exposed to client JavaScript. */
  requestCookies?: string[];
}

// TODO: Review this for cross-request security
// Use a global singleton so that both Mochi.ts (which calls .run()) and
// compiled SSR components (which call .getStore()) share the same instance.
// Without this, Bun's bundler creates a separate copy of the AsyncLocalStorage
// in each compiled component, breaking the context chain.
export const requestContext = pinGlobal('__mochi_request_context__', () => new AsyncLocalStorage<MochiRequestContext>());

/**
 * Returns the current request context. Available in any server-side code
 * running within a request (components, API handlers, helpers).
 *
 * ```svelte
 * <script>
 *   import { getRequestContext } from "mochi-framework";
 *   const { params, locals, url } = getRequestContext();
 * </script>
 * ```
 */
export function getRequestContext(): MochiRequestContext {
  const ctx = requestContext.getStore();
  if (!ctx) {
    throw new Error('getRequestContext() called outside of a request. ' + 'It is only available in server-side code running within a Mochi request handler.');
  }
  return ctx;
}

/**
 * Run an async function fully detached from the ambient request context.
 *
 * Used by the stateless render path (email/static). Inside `fn`, the request
 * context is cleared, so `getRequestContext()` (and anything built on it —
 * `cookies`, `url`) throws regardless of whether the caller is inside a request.
 *
 * Contract — do NOT loosen:
 *  - This wrapper owns the `await`, so the render runs while the store is cleared
 *    even though `render()` from svelte/server is a *lazy thenable* (the component
 *    executes in a microtask when awaited). `fn` may be a plain thunk returning
 *    that thenable; this wrapper awaits it inside the cleared scope.
 *  - `fn` MUST read any lazy getters (Svelte render `body`/`head`) and return plain
 *    values, so materialization also happens in the cleared scope — never return the
 *    live render object and read its getters at the call site (that reads under the
 *    restored ambient context).
 * The assertion is a tripwire if either invariant regresses.
 */
export async function renderDetached<T>(fn: () => Promise<T>): Promise<T> {
  return requestContext.exit(async () => {
    if (requestContext.getStore() !== undefined) {
      throw new Error('renderDetached: request context was not cleared — isolation failed');
    }
    return await fn();
  });
}
